### ISSUE TITLE
review: Neural Network Models for Pattern Recognition and Associative Memory

### ISSUE THREAD

**Issue by Chilinot** [mewmew/associative_memory#24]

**Comment by Chilinot** [comment]
This is a meta studie covering the grounds of associative memory models in ANNs. As well as many other important aspects of the field. I recommend we all give this a read through.

**Comment by mewmew** [comment]
Thanks Lucas, I'll take a look at this meta study as well. :)

**Comment by mewmew** [comment]
I'll look more closely at this meta-study at some point in the future. It would be interesting to further evaluate how it compares to our work. Marked as a future ambition. Closing for now.
