### ISSUE TITLE
meta: Models of Associative Memory

### ISSUE THREAD

**Issue by mewmew** [mewmew/associative_memory#25]
Identify key models of associative memory.
- Hopfield networks
- Boltzmann
- Memristor (artificial synapses)

Other key models, not included in the report.
- ~~Bidirectional associative memory~~
- ~~Autoassociative memory~~
- ~~Brain-states-in-a-box~~

From other fields (such as psychology).
- ~~Transderivational search (adding description in comment below)~~

**Comment by mewmew** [comment]
Related to issue #4.

**Comment by Chilinot** [comment]
I have found a reference to a model called "Brain-states-in-a-box" or "BSB" for short in paper #31. I have created an issue to review the paper that is referenced to this model, issue #32.

**Comment by mewmew** [comment]
> I have found a reference to a model called "Brain-states-in-a-box" or "BSB" for short in paper #31. I have created an issue to review the paper that is referenced to this model, issue #32.

Perfect! I'll add it to the list. If we have too many models, when we start to focus our research in a couple of weeks, we may select the most interesting from the list at that point.

**Comment by Chilinot** [comment]
Two more models listed by the same paper are:
Hamming network, issue #34 
Boltzmann Machine, issue #33

**Comment by Chilinot** [comment]
I have not assigned any of those three new papers to anyone, so if anyone is interested go ahead and grab any of the issues :)

**Comment by mewmew** [comment]
Transderivational search, used for resolving ambiguity and attaching semantical meaning to communication. Roughly corresponds to fuzzy search, which may be implemented using content-addressable memory.

As TDS is believed to play a fundamental part in making humans understand language, achieving fuzzy matching (or associative recall) may be crucial for future AI entities to gain an understanding of human language.

We still need to find a good paper explaining how the transderivational serach model for associative memory works. That is, if we deem this model relevant enough to go into depths to find out details about it.

**Comment by mewmew** [comment]
Hopfields may be used for auto-associative memory recall (recalling a memory from a fraction or piece of the memory, i.e. fill in the missing details).

Bidirectional associative memory may be used for hetroassociative memory (recalling one category from another; e.g. the pattern for _banana_ triggers the pattern for _monkey_ to fire in the brain)

**Comment by mewmew** [comment]
We ended up focusing on tree models (one each),
- Wenting: Hopfield Network
- Lucas: Boltzmann Machine
- Robin: Memory Resistor

Other models have been outlined in the description of this issue, and may be evaluated in the future. Closing this issue for now.
