### ISSUE TITLE
review: Anderson, James A. "A simple neural network generating an interactive memory." Mathematical Biosciences 14.3 (1972): 197-220

### ISSUE THREAD

**Issue by Chilinot** [mewmew/associative_memory#30]
A heavy and in-depth article. I have currently not read through it in its entirety, but I don't think we need a full review in the article as of now.

Short summary:
The article is a very in-depth analysis and discussion on how an interactive memory or what we would call a "Linear Associative Memory" today would be constructed using artificial neural networks. It even includes some sections where animal testing has been performed on monkeys in order to understand how neuron interact with each other.

**Comment by mewmew** [comment]
The paper was read and summarized by Lucas. As it includes both an abstract model and experimental verification (through animal testing), I'd be interested to see how well the model managed to describe the events observed in reality. Marking as a future ambition.
