### ISSUE TITLE
review: Anderson, James A., et al. "Distinctive features, categorical perception, and probability learning: Some applications of a neural model." Psychological Review 84.5 (1977): 413.

### ISSUE THREAD

**Issue by Chilinot** [mewmew/associative_memory#32]
According to an article I read (#31) this paper proposes a model called "Brain-states-in-a-box" or "BSB" for short.

**Comment by Chilinot** [comment]
The BSB model appears to be a variant of the Hopfield network.

**Comment by mewmew** [comment]
This was one of the models for associative memory we decided to leave out, to better focus on the remaining models. It may be a paper worth skimming through. Marked tentatively as a future ambition.
