### ISSUE TITLE
review: Ackley, David H., Geoffrey E. Hinton, and Terrence J. Sejnowski. "A learning algorithm for Boltzmann machines." Cognitive science 9.1 (1985): 147-169.

### ISSUE THREAD

**Issue by Chilinot** [mewmew/associative_memory#33]
This paper introduces what paper #31 calls a "Boltzmann Machine" that can be used for autoassociative memory.

**Comment by mewmew** [comment]
This is _the_ paper, introducing the theory behind the Boltzmann machine. Marked as a future ambition, as I would like to read this paper without a doubt.
