### ISSUE TITLE
meta: Licensing of work

### ISSUE THREAD

**Issue by mewmew** [mewmew/associative_memory#9]
@Chilinot and @chrisking2020, would you be alright with releasing our work into the public domain? Another alternative might be to use a Creative Commons license.

Personally, I'd be very happy to release the work into the public domain.

Cheers
- Robin

**Comment by Chilinot** [comment]
Public Domain is fine by me :)

**Comment by mewmew** [comment]
@Chilinot, wonderful :)

**Comment by chrisking2020** [comment]
Fine with me!

**Comment by slax32** [comment]
Alright with me👍

**Comment by mewmew** [comment]
Lovely! Closing this issue for now, as we've all agreed to release our work into the public domain.
